/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teiknari.v2.vidmot;

// Þessi klasi er notaður til að sýna leiðbeiningarglugga fyrir notkun á 
// forritinu
public class Adstod extends javax.swing.JFrame {

    // Smiðurinn fyrir gluggann.
    public Adstod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBakgrunnur = new javax.swing.JPanel();
        bLokaGlugga = new javax.swing.JButton();
        labLeidbeiningar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panOpnaHenda = new javax.swing.JPanel();
        spOpnaHenda = new javax.swing.JScrollPane();
        txtOpnaHenda = new javax.swing.JTextArea();
        labOpnaHenda = new javax.swing.JLabel();
        panVistaOpna = new javax.swing.JPanel();
        labVistaOpna = new javax.swing.JLabel();
        spVistaOpna = new javax.swing.JScrollPane();
        txtVistaOpna = new javax.swing.JTextArea();
        panAlmennt = new javax.swing.JPanel();
        labAlmennt = new javax.swing.JLabel();
        spAlmennt = new javax.swing.JScrollPane();
        txtAlmennt = new javax.swing.JTextArea();
        panStillingTola = new javax.swing.JPanel();
        labStillingTola = new javax.swing.JLabel();
        spStillingTola = new javax.swing.JScrollPane();
        txtStillingTola = new javax.swing.JTextArea();
        panTol1 = new javax.swing.JPanel();
        labTol1 = new javax.swing.JLabel();
        spTol1 = new javax.swing.JScrollPane();
        txtTol1 = new javax.swing.JTextArea();
        panTol2 = new javax.swing.JPanel();
        labTol2 = new javax.swing.JLabel();
        spTol2 = new javax.swing.JScrollPane();
        txtTol2 = new javax.swing.JTextArea();

        bLokaGlugga.setText("Loka glugga");
        bLokaGlugga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLokaGluggaActionPerformed(evt);
            }
        });

        labLeidbeiningar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        labLeidbeiningar.setForeground(new java.awt.Color(0, 0, 153));
        labLeidbeiningar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLeidbeiningar.setText("Leiðbeiningar");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtOpnaHenda.setEditable(false);
        txtOpnaHenda.setBackground(new java.awt.Color(240, 240, 240));
        txtOpnaHenda.setColumns(20);
        txtOpnaHenda.setRows(5);
        txtOpnaHenda.setText("- Nýtt blað:\n    1. Til þess að opna nýtt blað þarf að smella á \"Opna nýtt blað\"\n       hnappinn uppi í vinstra horninu. Forritið opnast þó sjálfkrafa\n       með eitt autt blað.\n    2. Þegar nýtt blað er opnað þá opnast gluggi þar sem hægt er að\n       velja vinnuheiti á myndina. Þó er hægt að skila auðu í\n       glugganum og þá fær myndin sjálfkrafa vinnuheitið\n       Mynd(númer myndar).\n    3. Hægt er að breyta vinnuheiti á mynd með því að fara í\n       Skrá - Breyta vinnuheiti á mynd.\n    4. Hægt er að hafa allt að 5 myndir opnar í einu.\n- Henda blaði:\n    1. Til þess að loka blaði er smellt á \"Henda blaði\" hnappinn uppi\n       í hægra horni viðmótsins.\n    2. Þegar smellt er á hnappinn er þeirri mynd lokað sem er opin í\n       viðmótinu þá stundina.\n    3. Ef búið er að teikna á blaðið, þegar loka á mynd, þá opnast\n       staðfestingargluggi áður en myndinni er svo varanlega hent.\n");
        spOpnaHenda.setViewportView(txtOpnaHenda);

        labOpnaHenda.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        labOpnaHenda.setForeground(new java.awt.Color(0, 0, 153));
        labOpnaHenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labOpnaHenda.setText("Að opna og henda blöðum");

        javax.swing.GroupLayout panOpnaHendaLayout = new javax.swing.GroupLayout(panOpnaHenda);
        panOpnaHenda.setLayout(panOpnaHendaLayout);
        panOpnaHendaLayout.setHorizontalGroup(
            panOpnaHendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labOpnaHenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(panOpnaHendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spOpnaHenda)
                .addContainerGap())
        );
        panOpnaHendaLayout.setVerticalGroup(
            panOpnaHendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panOpnaHendaLayout.createSequentialGroup()
                .addComponent(labOpnaHenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spOpnaHenda, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Opna/henda blöðum", panOpnaHenda);

        labVistaOpna.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        labVistaOpna.setForeground(new java.awt.Color(0, 0, 153));
        labVistaOpna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labVistaOpna.setText("Að vista og opna myndir");

        txtVistaOpna.setEditable(false);
        txtVistaOpna.setBackground(new java.awt.Color(240, 240, 240));
        txtVistaOpna.setColumns(20);
        txtVistaOpna.setRows(5);
        txtVistaOpna.setText("- Vista mynd:\n    1. Ef vista á mynd þarf hún að vera valin á viðmóti.\n    2. Til þess að vista er farið í Skrá - Vista mynd.\n    3. Einungis er hægt að vista myndir sem PNG myndir.\n    4. Þegar vista glugginn er opnaður er sjálfkrafa lagt til nafn sem er\n       þá sama nafn og vinnuheiti myndarinnar hefur. Þó er hægt að breyta\n       því ef vill.\n    5. Passa verður uppá að nafn myndar endi á .png þegar vistað er. \n- Opna mynd:\n    1. Til þess að opna mynd er farið í Skrá - Opna mynd.\n    2. Þessi valmöguleiki er fyrst og fremst hugsaður til þess að opna\n       myndir sem hafa áður verið teiknaðar í þessu forriti, og því er\n       ekki hægt að hafa áhrif á stærð myndarinnar þegar hún er opnuð.\n    3. Þrátt fyrir atriði 2. er hægt að opna flestar myndir af tagi PNG\n       og einnig er hægt að opna myndir af tagi JPEG. Hér verður þó að\n       hafa í huga að ef myndin er minni en blaðið þá opnast myndin uppi\n       í hægra horni blaðsins, og ef myndin er stærri, þá er einungis\n       hægt að sjá hluta af myndinni.");
        spVistaOpna.setViewportView(txtVistaOpna);

        javax.swing.GroupLayout panVistaOpnaLayout = new javax.swing.GroupLayout(panVistaOpna);
        panVistaOpna.setLayout(panVistaOpnaLayout);
        panVistaOpnaLayout.setHorizontalGroup(
            panVistaOpnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labVistaOpna, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(panVistaOpnaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spVistaOpna)
                .addContainerGap())
        );
        panVistaOpnaLayout.setVerticalGroup(
            panVistaOpnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVistaOpnaLayout.createSequentialGroup()
                .addComponent(labVistaOpna, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spVistaOpna, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vista/opna myndir", panVistaOpna);

        labAlmennt.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        labAlmennt.setForeground(new java.awt.Color(0, 0, 153));
        labAlmennt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labAlmennt.setText("Almennt um myndvinnsluna");

        txtAlmennt.setBackground(new java.awt.Color(240, 240, 240));
        txtAlmennt.setColumns(20);
        txtAlmennt.setRows(5);
        txtAlmennt.setText("- Stíga skref til baka (e. undo):\n    1. Ef mistök hafa orðið við teikningu, t.d. lína teiknuð sem\n       heppnaðist ekki nógu vel, þá er hægt smella á takkann með bláu\n       örinni sem vísar til vinstri, uppi í hægra horni viðmótsins.\n    2. Hægt er að stíga öll skref til baka er varða teikningu á blaðinu\n       nema fötuaðgerðir.\n    3. Ef reynt er að hella með fötu yfir mynd kemur staðfestingargluggi\n       til að koma í veg fyrir óhöpp. Ef hellt er á bakgrunn er\n       einfaldlega hægt að velja gamla litinn og hella á ný.\n- Stíga skref áfram (e. redo):\n    1. Hægt er að smella á takkann með bláu örina til hægri, uppi í hægra\n       horni viðmótsins, til að stíga skref áfram.\n    2. Þetta er þó einungis hægt að gera eftir undo aðgerðir, ef t.d. ýtt\n       var of oft á undo takkann.\n- Hreinsa mynd:\n    1. Hægt er að hreinsa mynd hvenær sem er með því að smella á\n       \"Hreinsa blað\".\n    2. Þessi aðgerð hreinsar alla teikningu af blaðinu sem er opið, þá\n       stundina, á viðmótinu.\n    3. Ef teiknað hefur verið á blaðið kemur upp staðfestingargluggi áður\n       en blað er svo varanlega hreinsað.");
        spAlmennt.setViewportView(txtAlmennt);

        javax.swing.GroupLayout panAlmenntLayout = new javax.swing.GroupLayout(panAlmennt);
        panAlmennt.setLayout(panAlmenntLayout);
        panAlmenntLayout.setHorizontalGroup(
            panAlmenntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labAlmennt, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(panAlmenntLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spAlmennt)
                .addContainerGap())
        );
        panAlmenntLayout.setVerticalGroup(
            panAlmenntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlmenntLayout.createSequentialGroup()
                .addComponent(labAlmennt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spAlmennt, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Almenn myndvinnsla", panAlmennt);

        labStillingTola.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        labStillingTola.setForeground(new java.awt.Color(0, 0, 153));
        labStillingTola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labStillingTola.setText("Stilling tóla fyrir teikningu");

        txtStillingTola.setEditable(false);
        txtStillingTola.setBackground(new java.awt.Color(240, 240, 240));
        txtStillingTola.setColumns(20);
        txtStillingTola.setRows(5);
        txtStillingTola.setText("- Um liti:\n    1. Hægt er að velja liti með því að smella á viðeigandi litahjól í\n       litahlutanum Litur eða hlutanum Fylling, eftir því sem við á, sem\n       eru efst í viðmótinu fyrir miðju.\n    2. Hægt er að sjá núverandi valda liti í stóru litagluggunum í hvorum\n       litahlutanum fyrir sig.\n    3. liturinn í hlutanum Litur hefur áhrif á öll tól sem hægt er að\n       nota við teikningu, einnig texta-tólið. Í tilviki forma hefur\n       þessi litur áhrif á útlínurnar.\n    4. Liturinn Fylling hefur einungis áhrif á litinn sem er notaður í\n       fyllingu á formum.\n    5. Þegar litir hafa verið valdir vistast nýlegustu litirnir í litlu\n       litagluggunum þremur í viðeigandi litahluta. Hægt er að smella á\n       litagluggana til að setja þann lit sem núverandi lit.\n- Um stærð:\n    1. Stærð hefur áhrif á öll tól sem hægt er að nota við teikningu nema\n       augljóslega fötuna, sem fyllir alla myndina, og svo\n       þrívíddarkassana.\n    2. Í tilviki forma hefur stærð áhrif á stærð útlína.\n- Um gegnsæi:\n    1. Hægt er að stilla gegnsæi allra tóla, nema fötu, neðarlega í\n       vinstra horni viðmóts.");
        spStillingTola.setViewportView(txtStillingTola);

        javax.swing.GroupLayout panStillingTolaLayout = new javax.swing.GroupLayout(panStillingTola);
        panStillingTola.setLayout(panStillingTolaLayout);
        panStillingTolaLayout.setHorizontalGroup(
            panStillingTolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labStillingTola, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(panStillingTolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spStillingTola)
                .addContainerGap())
        );
        panStillingTolaLayout.setVerticalGroup(
            panStillingTolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStillingTolaLayout.createSequentialGroup()
                .addComponent(labStillingTola, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spStillingTola, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stilling tóla", panStillingTola);

        labTol1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        labTol1.setForeground(new java.awt.Color(0, 0, 153));
        labTol1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTol1.setText("Um pensil, strokleður og spreybrúsa");

        txtTol1.setEditable(false);
        txtTol1.setBackground(new java.awt.Color(240, 240, 240));
        txtTol1.setColumns(20);
        txtTol1.setRows(5);
        txtTol1.setText("- Almennt:\n    1. Í upphafi er ekkert tól valið og því ekkert hægtað teikna á mynd\n       fyrr en tól eða form er valið.\n    2. Einungis er hægt að velja eitt tól eða form í einu.\n- Pensill:\n    1. Pensillinn virkar eins og venjulegur pensill, þ.e. hægt er að\n       teikna hvað sem er fríhendis.\n    2. Ábending 1: Ef gegnsæi pensils er lækkað í u.þ.b. 50%, þá fást\n       nokkurs konar tússpennaáhrif.\n    3. Ábending 2: Ef gegnsæið er lækkað enn meira, t.d. í u.þ.b. 15%,\n       þá fást nokkurs konar vatnslitaáhrif.\n- Strokleður:\n    1. Strokleðrið virkar eins og pensillinn nema það tekur alltaf mið\n       af bakgrunnslitnum í hvert sinn, þannig ekki þarf að hafa áhyggjur\n       af því að stroka út litinn ef fötu var hellt yfir.\n    2. Stærð hefur aðeins öðruvísi áhrif á strokleðrið en önnut tól, þ.e.\n       strokleðrið er alltaf tiltekinni fastri stærð stærri, sem eykur\n       þægindi.\n- Spreybrúsi:\n    1. Brúsinn er fríhendis teiknitól.\n    2. Spreyið kemur talsvert hægar en maður er e.t.v. vanur í t.d.\n       Microsoft Paint, en það eykur stjórnun á spreyinu sjálfu.");
        spTol1.setViewportView(txtTol1);

        javax.swing.GroupLayout panTol1Layout = new javax.swing.GroupLayout(panTol1);
        panTol1.setLayout(panTol1Layout);
        panTol1Layout.setHorizontalGroup(
            panTol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTol1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(panTol1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTol1)
                .addContainerGap())
        );
        panTol1Layout.setVerticalGroup(
            panTol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTol1Layout.createSequentialGroup()
                .addComponent(labTol1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTol1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tól 1/2", panTol1);

        labTol2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        labTol2.setForeground(new java.awt.Color(0, 0, 153));
        labTol2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTol2.setText("Um Texta-tólið og form");

        txtTol2.setEditable(false);
        txtTol2.setBackground(new java.awt.Color(240, 240, 240));
        txtTol2.setColumns(20);
        txtTol2.setRows(5);
        txtTol2.setText("- Texta-tólið:\n    1. Þegar texta-tólið er valið þá er hægt að smella á staðsetningu á\n       blaðinu þar sem textinn á að birtast.\n    2. Þegar smellt er á blaðið þá opnast gluggi þar sem hægt er að skrifa\n       textann sem er svo settur á blaðið.\n- Form:\n    1. Hægt er að velja á milli ýmissa forma sem hegða sér öll sambærilega\n       nema þrívíddarkassinn.\n    2. Ef t.d. ferhyrningur er valinn þá er hægt að smella hvar sem er á\n       blaðið og draga svo með músinni í hvaða átt sem er þar til réttu\n       formi er náð.\n    3. Þegar músin er dregin með form þá sést allan tímann hvernig formið\n       myndi líta út ef músinni væri sleppt á hverri stundu.\n    4. Hægt er að velja að hafa form fyllt með öðrum lit með því að smella\n       á \"fylling\" fyrir neðan formin í formglugganum fyrir miðju vinstra\n       megin. Einnig er hægt að smella beint á fyllingarlitinn og þá\n       stillist \"fylling\" sjálfkrafa.\n    5. Þegar smellt er á þrívíddarkassann verður sjálfkrafa ekki hægt að\n       velja stærð, þar sem hún getur ekki haft áhrif á útlínurnar, og\n       einnig er \"fylling\" sjálfkrafa stillt og ekki er hægt að hafa áhrif\n       á hana.");
        spTol2.setViewportView(txtTol2);

        javax.swing.GroupLayout panTol2Layout = new javax.swing.GroupLayout(panTol2);
        panTol2.setLayout(panTol2Layout);
        panTol2Layout.setHorizontalGroup(
            panTol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTol2, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(panTol2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTol2)
                .addContainerGap())
        );
        panTol2Layout.setVerticalGroup(
            panTol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTol2Layout.createSequentialGroup()
                .addComponent(labTol2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTol2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tól 2/2", panTol2);

        javax.swing.GroupLayout panBakgrunnurLayout = new javax.swing.GroupLayout(panBakgrunnur);
        panBakgrunnur.setLayout(panBakgrunnurLayout);
        panBakgrunnurLayout.setHorizontalGroup(
            panBakgrunnurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBakgrunnurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBakgrunnurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labLeidbeiningar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLokaGlugga))
                .addContainerGap())
        );
        panBakgrunnurLayout.setVerticalGroup(
            panBakgrunnurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBakgrunnurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labLeidbeiningar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bLokaGlugga)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panBakgrunnur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBakgrunnur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Atburðahandler fyrir takkann "Loka Glugga" á viðmótinu.
    // Sér til þess að glugginn hverfi af skjánum.
    private void bLokaGluggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLokaGluggaActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_bLokaGluggaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adstod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adstod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adstod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adstod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adstod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLokaGlugga;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labAlmennt;
    private javax.swing.JLabel labLeidbeiningar;
    private javax.swing.JLabel labOpnaHenda;
    private javax.swing.JLabel labStillingTola;
    private javax.swing.JLabel labTol1;
    private javax.swing.JLabel labTol2;
    private javax.swing.JLabel labVistaOpna;
    private javax.swing.JPanel panAlmennt;
    private javax.swing.JPanel panBakgrunnur;
    private javax.swing.JPanel panOpnaHenda;
    private javax.swing.JPanel panStillingTola;
    private javax.swing.JPanel panTol1;
    private javax.swing.JPanel panTol2;
    private javax.swing.JPanel panVistaOpna;
    private javax.swing.JScrollPane spAlmennt;
    private javax.swing.JScrollPane spOpnaHenda;
    private javax.swing.JScrollPane spStillingTola;
    private javax.swing.JScrollPane spTol1;
    private javax.swing.JScrollPane spTol2;
    private javax.swing.JScrollPane spVistaOpna;
    private javax.swing.JTextArea txtAlmennt;
    private javax.swing.JTextArea txtOpnaHenda;
    private javax.swing.JTextArea txtStillingTola;
    private javax.swing.JTextArea txtTol1;
    private javax.swing.JTextArea txtTol2;
    private javax.swing.JTextArea txtVistaOpna;
    // End of variables declaration//GEN-END:variables
}
